---
title: "Lab 06 - Ugly charts and Simpson's paradox"
author: "Heather Hawkins"
date: "02-14-23"
output: github_document
---

### Load packages and data

```{r load-packages, message = FALSE}
library(tidyverse) 
library(dsbox)
library(mosaicData) 
```

### Exercise 1

```{R reading}
staff <- read_csv("data/instructional-staff.csv")

view(staff)

#Turning into a longer data frame
staff_long <- staff %>%
  pivot_longer(cols = -faculty_type, names_to = "year") %>%
  mutate(value = as.numeric(value))

#Plotting long data
staff_long %>%
  ggplot(aes(x = year, y = value, color = faculty_type)) +
  geom_line()

#Fixing data points
staff_long %>%
  ggplot(aes(x = year,
             y = value,
             group = faculty_type,
             color = faculty_type)) +
  geom_line()+ labs(title="Instructional Staff Employment Trends ", subtitle="American Association of University Professors (AAUP)",
   x="Year", y="Number of Hires", color="Faculty Type")
```

### Exercise 2

Suppose the objective of this plot was to show that the proportion of part-time faculty have gone up over time compared to other instructional staff types. > What changes would you propose making to this plot to tell this story?

I would group all of the other groups (Full-Time Non Tenure, Full-Time Tenure-Track, Full-Time Tenured, and Grad Student Employees) data together, and compare that data to the Part-Time data within the graph. 

```{R Staff}
staff_compare <- staff_long %>%
  subset(faculty_type!="Part-Time Faculty")

staff_compare<- staff_compare %>%
  group_by(year)%>%
  summarise(mean_pct=mean(value),
            faculty_type="other_types")

pt_faculty <- staff_long %>%
  subset(faculty_type=="Part-Time Faculty")

#Plotting
staff_compare %>%
  ggplot()+ geom_line(data=pt_faculty,aes(x = year,
           y = value,
           group = faculty_type,
           color = faculty_type))+
geom_line(data=staff_compare,aes(x = year,
           y = mean_pct,
           group = faculty_type,
           color = faculty_type))+ labs(title="Instructional Staff Employment Trends ", subtitle="American Association of University Professors (AAUP)",
   x="Year", y="Number of Hires", color="Faculty Type")
```

### Exercise 3

Can you help them make improve it? First, brainstorm how you would improve it. Then create the improved visualization and document your changes/decisions with bullet points. It’s ok if some of your improvements are aspirational, i.e. you don’t know how to implement it, but you think it’s a good idea. Implement what you can and leave notes identifying the aspirational improvements that could not be made.

To improve the fisheries graph, we could plot the data with a cap scale- since there are only a few countries that farm and capture an enormous amount of fish. 


Or maybe even focus on the TOP countries that farm and capture fish. 
Since this Lab is about converting data and comparing, Ill focus on the second method


```{R Fish}
fisheries <- read_csv("data/fisheries.csv")

fisheries_long <- fisheries %>%
  pivot_longer(cols = -country, names_to = "Fishing_Type") %>%
  filter(Fishing_Type %in% c("capture", "aquaculture")) %>%
  mutate(value = as.numeric(value))

#Plotting

fisheries_long %>%
  filter(country %in% c("China", "Indonesia", "India", "Vietnam", "United States")) %>%
  ggplot(aes(group = Fishing_Type, color= Fishing_Type, y=value, x=country)) + labs(title="Tons of Fish Produced by Top Fishing Countries ",
   x="Countries", y="Number of Fish by Tons", color="Fishing Types")+   geom_line()


```
### Exercise 4

```{R Loading}
library(tidyverse) 
library(mosaicData) 

data(Whickham)

view(Whickham)
```
## Part 1
What type of study do you think these data come from: observational or experiment? Why?

Observational, since this is quasi-experimental data (i.e., we are not making people smokers or non smokers, not making them dead or alive) there are no manipulations used, therefore we can just collect and observe the data.

## Part 2
How many observations are in this dataset? What does each observation represent?

There are 1314 observations, Each observation is a person in Whickham. 

```{R sumdata}
summary(Whickham)
```

## Part 3
How many variables are in this dataset? What type of variable is each? Display each variable using an appropriate visualization.

There are only 3 variables: Outcome (Dead or Alive), Smoker(non and smoker), and Age. Outcome and Smoker are categorical data, while age is numeric.

```{R view variables}

Whickham %>%
ggplot(aes(x=age, fill=smoker)) +geom_bar()+ facet_wrap(~outcome)+ labs (title= "Smokers in Whickham", x= "Age", y= "Number of People" ) + labs(fill="Smoker") 
```
## Part 4
What would you expect the relationship between smoking status and health outcome to be?

I expect a negative correlation, those who are dead are more likely to be smokers, and those who are alive are more likely to be non-smokers

## Part 5

There doesn't seem to be a difference or a significant relationship between smoking and health. dead and alive individuals are of almost equal amounts of smokers and non-smokers. 

on the conditional probabilites, it seems as if it was the opposite- smokers were likely likely to die than non-smokers

```{R Visual}

Whickham %>%
ggplot(aes(fill = outcome, x = smoker))+
geom_bar()+ labs (title= "Relationship Between Health and Smoking", x= "Smoker", subtitle= "For people in Whickham", y= "Number of People" ) + labs(fill="Outcome") 

Whickham %>%
  count(smoker, outcome) %>%
  group_by(smoker) %>%
  mutate(prob_dead = n/sum(n))
```

## Part 6
Create a new variable called age_cat using the following scheme:
age <= 44 ~ "18-44"
age > 44 & age <= 64 ~ "45-64"
age > 64 ~ "65+"

```{R age-cat}
Whickham_Age <- Whickham %>% 
  mutate(age_cat = case_when(
    age <= 44 ~ "18-44",
    age > 44 & age <= 64 ~ "45-64",
    age > 64 ~ "65+"))
```


## Part 7

What changed? 
As you can see, those who were 65+ were more likely to be dead 20 years later, and those who were 18-44 were least likely to be dead 20 years later.

Additionally, you can see that there were not many smokers in the 65+ range. 45-64 was a little better, and 18-44 was pretty evenly split. 

If we look at the death of smokers in the 65+ cat and compare it to those who are alive, MOST smokers died 20 years later. Same as non-smokers. 

What might explain this change? 

The data became categorized into groups. 
Because of this, we are able to see the points mentioned above. the age ratio, and the amount of smokers in the 65+ scewed the data to make the overall data seem as if there wasnt a difference in the health outcome of smokers and non-smokers. 


```{R view}
Whickham_Age %>%
  count(smoker, age, outcome)

Whickham_Age %>%
ggplot(aes(fill = smoker, x = outcome))+
facet_wrap(~age_cat)+geom_bar()+ labs (title= "Smokers in Whickham", x= "Health Outcome", y= "Number of People" ) + labs(fill="Smoker") 

Whickham_Age %>%
ggplot(aes(x=age, fill=smoker)) +geom_bar()+ facet_wrap(~outcome)+ labs (title= "Smokers in Whickham", x= "Age", y= "Number of People" ) + labs(fill="Smoker")+ facet_wrap(~age_cat) 
```
```